config/routes.rb
LyrikApp::Application.routes.draw do

  get "discover/index"
  get "dashboard/index"

  resources :sessions, only: [:new, :create] do 
    collection do
      delete nil, to: "sessions#destroy", as: :destroy
    end
  end

  resources :users

  resources :comments

  resources :songs

  resources :genres

  root :to => 'index#index'

  resources :posts do
    get 'page/:page', action: :index, on: :collection
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all
    @genres = Genre.all
    @songs = Song.where(user_id: current_user.id)
    @comments = Comment.where(user_id: current_user.id)
  end
end

app/views/dashboard/index.html.erb
<%= content_for :title, 'Dashboard' %>

<div class="box">
  <h2>My songs</h2>
  <table>
    <% @songs.each do |song| %>
    <tr>
      <td><%= song.user.username %></td>
      <td><%= song.name %></td>
      <td><%= audio_tag song.lyrik, controls: true %></td>
      <td><%= song.created_at.to_formatted_s(:long) %></td></td>
      <td><%= song.rating %></td>
      <td><%= link_to 'Show', song %></td>
      <td><%= link_to 'Edit', edit_song_path(song) %></td>
      <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>      
    </tr>
    <% end %>
  </table>
</div>

<div class="box">
  <h2>My comments:</h2>
  <table>
    <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= comment.song_id %></td>
      <td><%= comment.created_at.to_formatted_s(:long) %></td>
      <td><%= link_to 'Show', comment %></td>
      <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
</div>

<div class="box">
  <h2>Manage site:</h2>
  <table>
    <tr>
      <li><%= link_to 'users', users_path %></li>
      <li><%= link_to 'genres', genres_path %></li>
      <li><%= link_to 'songs', songs_path %></li>
      <li><%= link_to 'comments', comments_path %></li>
    </tr>
  </table>
</div>