config/routes.rb
LyrikApp::Application.routes.draw do

  get "discover/index"
  get "dashboard/index"

  resources :sessions, only: [:new, :create] do 
    collection do
      delete nil, to: "sessions#destroy", as: :destroy
    end
  end

  resources :users

  resources :comments

  resources :songs

  resources :genres

  root :to => 'index#index'

  resources :posts do
    get 'page/:page', action: :index, on: :collection
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :song_id, :user_id

  belongs_to :song
  belongs_to :user

  validates :content, length: { in: 1..500 }



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @comments = Comment.all
    authorize! :index, @comment
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def show
    @comment = Comment.find(params[:id])
    authorize! :show, @comment
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  def new
    @comment = Comment.new
    authorize! :new, @comment 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    authorize! :edit, @comment
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.json { render json: root_path, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

<div class="box">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.collection_select :song_id, Song.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<div class="box">
  <table>
    <tr>
      <th>Content</th>
      <th>Song</th>
      <th>User</th>
      <th>Date</th>
    </tr>

    <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= comment.song.name %></td>
      <td><%= comment.user.name %></td>
      <td><%= comment.created_at.to_formatted_s(:long) %></td>
      <td><%= link_to 'Show', comment %></td>
      <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
  <p>
    <b>Content:</b>
    <%= @comment.content %>
  </p>

  <p>
    <b>Song:</b>
    <%= @comment.song_id %>
  </p>

  <p>
    <b>User:</b>
    <%= @comment.user.name %>
  </p>

  <%= link_to 'Edit', edit_comment_path(@comment) %> |
  <%= link_to 'Back', discover_index_path %>

</div>