config/routes.rb
LyrikApp::Application.routes.draw do

  get "discover/index"
  get "dashboard/index"

  resources :sessions, only: [:new, :create] do 
    collection do
      delete nil, to: "sessions#destroy", as: :destroy
    end
  end

  resources :users

  resources :comments

  resources :songs

  resources :genres

  root :to => 'index#index'

  resources :posts do
    get 'page/:page', action: :index, on: :collection
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name, :rating, :user_id, :lyrik, :genre_ids, :comment_ids

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :genres

  validates :name, presence: true, uniqueness: true
  validates :lyrik, presence: true, uniqueness: true

  mount_uploader :lyrik, LyrikUploader

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authenticate_user!, except: :index

  def index   
    @q = Song.search(params[:q])
    # authorize! :index, @song 
    @songs = @q.result.order(:created_at).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  def show
    @song = Song.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  def new
    @song = Song.new
    authorize! :new, @song 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  def edit
    @song = Song.find(params[:id])  
    authorize! :edit, @song
  end

  def create
    @song = Song.new(params[:song])
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @song = Song.find(params[:id])
    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    authorize! :index, @song 
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  
<% if @song.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>
    <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="box">
  <div class="field">
    <%= f.label :user_id, 'author' %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name, 'title' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lyrik, 'attach' %><br />
    <%= f.file_field :lyrik, value: @song.lyrik %>
  </div>
  <div class="field">
    <% Genre.all.each do |genre| %>
    <%= check_box_tag "song[genre_ids][]", genre.id, @song.genres.include?(genre), id: "song_genre_ids_#{genre.id}" %>
    <%= f.label :genre_ids, genre.name, for: "song_genre_ids_#{genre.id}" %>
    <br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/songs/edit.html.erb
<%= content_for :title, 'Edit' %>

<h1>edit song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |

app/views/songs/index.html.erb
<%= content_for :title, 'Lyriks' %>

<h1>All songs</h1>

<div class="box">
  <table>
    <% @songs.each do |song| %>
    <tr>
      <td><%= image_tag song.user.image.thumb %></td>
      <td><%= song.user.username %></td>
      <td><%= song.name %></td>
      <td><%= audio_tag song.lyrik, controls: true %></td>
      <td><%= song.created_at.to_formatted_s(:long) %></td>
      <td><%= song.rating %></td>
      <td><%= link_to 'Show', song %></td>
      <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    <%= paginate @songs %>
  </table>
  <br />
  <%= link_to 'Back', dashboard_index_path %>
</div>

app/views/songs/new.html.erb
<%= content_for :title, 'Upload' %>

<h2>upload a new song</h2>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<%= content_for :title, 'Lyrik' %>

<p id="notice"><%= notice %></p>

<div class="box">
  <h2>Author:</h2>
  <p><%= @song.user.username %></p>
  <p><%= image_tag @song.user.image, class: 'user_image' %></p>
  
  <h2>Title:</h2>
  <p><%= @song.name %></p>
  <p><%= audio_tag @song.lyrik, controls: true, class: 'song_lyrik' %></p>

  <h2>Genre(s):</h2>
  <p><% @song.genres.each do |genre| %>
      <%= genre.name %>
    <% end %></p>

  <p><%= link_to 'Edit', edit_song_path(@song) %> | 
    <%= link_to "Leave a comment", new_comment_path %></p>
</div>

<div class="comment_box">
  <h2>Comments:</h2>    
    <% @song.comments.each do |comment| %>
      <%= comment.user.name %> |
      <%= comment.created_at.to_formatted_s(:long) %></br>
      <%= comment.content %></br>
      <%= link_to 'Delete comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</div>