config/routes.rb
LyrikApp::Application.routes.draw do

  get "discover/index"
  get "dashboard/index"

  resources :sessions, only: [:new, :create] do 
    collection do
      delete nil, to: "sessions#destroy", as: :destroy
    end
  end

  resources :users

  resources :comments

  resources :songs

  resources :genres

  root :to => 'index#index'

  resources :posts do
    get 'page/:page', action: :index, on: :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  </head>
  <body style="<%= show_user_bg(current_user) %>">  
    <div class="wrapper <%= show_default_bg(current_user) %>">
      <header>
        <a href="/">
          <h1>Lyrik</h1>
        </a>
        <nav>
          <ul>
            <li><%= link_to "discover", discover_index_path %></li>
            <li class="search1"><%= search_form_for @q do |f| %>
                <%= f.text_field :name_or_user_name_or_user_username_cont, placeholder: "song, user, username" %></li>
            <li class="search2"><%= f.submit %>
            <% end %></li>
            <li><%= link_to "dashboard", dashboard_index_path %></li>
            <li><%= link_to "profile", current_user %></li>
            <li><%= link_to "upload", new_song_path %></li>
            <li><% if current_user %>
                  <%= current_user.email %>
                  <%= link_to "logout", destroy_sessions_path, method: :delete %>
                <% else %>
                    <%= link_to "login", new_session_path %></li>
                <li><%= link_to "sign up", new_user_path %></li>
                <% end %></li>
          </ul>
        </nav>
      </header>
      <div id="container">
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>